import { config } from '$site_config/config.js';
/* #### SITE #### */
const site = {
	domain: 'milkjs.com',
	url: 'https://milkjs.com',
	photo: '/img/profile_1200x1200.jpg',
	photo_avif: '/img/profile_1200x1200.avif',
	photo_webp: '/img/profile_1200x1200.webp',
	logo: '/milk/img/logo_milk.svg',
	logo_width: '60',
	logo_height: '60',
	title: 'Milk',
	tagline: 'Milk, it does a website good.',
	organization: 'Milk.js',
	first_name: 'Milk',
	last_name: 'JS',
	middle_name: '',
	prefix_name: '',
	suffix_name: '',
	nick_name: '',
	email_address: 'info@milkjs.com',
	phone: '',
	fax: '',
	address: '',
	address2: '',
	city: '',
	state: '',
	state_abbr: '',
	zip: '',
	country: '',
	country_abbr: '',
	hours_of_operation: '',
	hours_of_operation_dt: '',
	price_range: '$',
	category: '',
	description: '',
	keywords: '',
	established: '',
	latitude: '',
	longitude: '',
	google_maps: '', // shortened direct
	google_maps_embed: '', // from ifram embed src
	google_maps_image: '',
	google_maps_image_webp: '',
	google_maps_image_avif: '',
	google_business: '',
	facebook: '',
	facebook_photo: 'https://milkjs.com/img/socialmedia_1200x630.jpg',
	facebook_type: 'website',
	twitter: '',
	twitter_photo: 'https://milkjs.com/img/socialmedia_1200x630.jpg',
	instagram: '',
	linkedin: '',
	youtube: '',
	vimeo: '',
	rss: '',
	blog: '',
	etsy: '',
	yelp: '',
	airbnb: '',
	tiktok: '',
	snapchat: '',
	pinterest: '',
	vcf_file: '',
	calendar: ''
};
if (config?.lock_config) { Object.freeze(site); };
export { site };