<svelte:head>
	<link async rel="icon" href="/favicon.ico" />
	<link
		async
		rel="icon"
		type="image/png"
		href="/ico/favicon-16x16.png"
		sizes="16x16"
	/>
	<link
		async
		rel="icon"
		type="image/png"
		href="/ico/favicon-32x32.png"
		sizes="32x32"
	/>
	<link
		async
		rel="icon"
		type="image/png"
		href="/ico/favicon-64x64.png"
		sizes="64x64"
	/>
	<link
		async
		rel="icon"
		type="image/png"
		href="/ico/favicon-96x96.png"
		sizes="96x96"
	/>
	<link
		async
		rel="icon"
		type="image/png"
		href="/ico/favicon-128x128.png"
		sizes="128x128"
	/>
	<link
		async
		rel="icon"
		type="image/png"
		href="/ico/favicon-256x256.png"
		sizes="256x256"
	/>
	<link
		async
		rel="icon"
		type="image/png"
		href="/ico/favicon-512x512.png"
		sizes="512x512"
	/>
	<link
		async
		rel="icon"
		type="image/png"
		href="/ico/favicon-1024x1024.png"
		sizes="1024x1024"
	/>
</svelte:head>
